spring.application.name=yolo-backend
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

roboflow.api-key=${ROBOFLOW_API_KEY}
roboflow.model-id=${ROBOFLOW_MODEL_ID}